[package]
name = "important-separators"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27.2"
egui = "0.27.2"
egui_graphs = "0.20.0"
itertools = "0.13.0"
petgraph = "0.6.5"
rand = "0.8.5"
